#ifndef RANKINGERRCODES_H
#define RANKINGERRCODES_H

namespace RankingApp
{
  enum class ERR {
    SUCCESS,
    FILE_NOT_EXISTING_OR_INVALID,
    FILE_ALREADY_EXISTS,
    INVALID_FILENAME,
    PLAYER_EXISTS,
    DATABASE_ERROR,
    INVALID_NAME,
    PLAYER_IS_ALREADY_ENABLED,
    START_DATE_TOO_EARLY,
    PLAYER_IS_NOT_ENABLED,
    END_DATE_TOO_EARLY,
    IDENTICAL_PLAYERS_IN_MATCH,
    INVALID_SCORE,
    INACTIVE_PLAYERS_IN_MATCH,
  };
}

#endif  /* RANKINGERRCODES */
